fix: resolves 'TypeError: typeParameters.params is not iterable' and 'TypeError: Cannot read properties of undefined (reading 'name')'
The first change fixed:

```
> ramblefeed-workspace@0.1.0 lint
> eslint --max-warnings 65

Oops! Something went wrong! :(

ESLint: 9.39.0

TypeError: typeParameters.params is not iterable
Occurred while linting /Users/scott/src/activescott/ramblefeed/packages/web-app/app/lib/components/note-card.tsx:15
Rule: "@typescript-eslint/unified-signatures"
    at getIsTypeParameter (/Users/scott/src/activescott/ramblefeed/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:242:44)
    at checkOverloads (/Users/scott/src/activescott/ramblefeed/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:99:37)
    at checkScope (/Users/scott/src/activescott/ramblefeed/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:344:30)
    at ruleErrorHandler (/Users/scott/src/activescott/ramblefeed/node_modules/eslint/lib/linter/linter.js:1173:33)
    at /Users/scott/src/activescott/ramblefeed/node_modules/eslint/lib/linter/source-code-visitor.js:76:46
    at Array.forEach (<anonymous>)
    at SourceCodeVisitor.callSync (/Users/scott/src/activescott/ramblefeed/node_modules/eslint/lib/linter/source-code-visitor.js:76:30)
    at /Users/scott/src/activescott/ramblefeed/node_modules/eslint/lib/linter/source-code-traverser.js:306:18
    at Array.forEach (<anonymous>)
    at SourceCodeTraverser.traverseSync (/Users/scott/src/activescott/ramblefeed/node_modules/eslint/lib/linter/source-code-traverser.js:305:10)
```

The second change just below there then fixed the following error and lint then was able to run successfully. I'm not sure the cause of the first one the second one was surprisingly straightforward, but a little too surprising. Maybe the first fix allowed the second error to manifest?

```
> ramblefeed-workspace@0.1.0 lint
> eslint --max-warnings 65

Oops! Something went wrong! :(

ESLint: 9.39.0

TypeError: Cannot read properties of undefined (reading 'name')
Occurred while linting /Users/scott/src/activescott/ramblefeed/packages/web-app/app/lib/repositories/note.ts:689
Rule: "@typescript-eslint/unified-signatures"
    at getIsTypeParameter (/Users/scott/src/activescott/ramblefeed/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:243:32)
    at checkOverloads (/Users/scott/src/activescott/ramblefeed/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:99:37)
    at checkScope (/Users/scott/src/activescott/ramblefeed/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js:344:30)
    at ruleErrorHandler (/Users/scott/src/activescott/ramblefeed/node_modules/eslint/lib/linter/linter.js:1173:33)
    at /Users/scott/src/activescott/ramblefeed/node_modules/eslint/lib/linter/source-code-visitor.js:76:46
    at Array.forEach (<anonymous>)
    at SourceCodeVisitor.callSync (/Users/scott/src/activescott/ramblefeed/node_modules/eslint/lib/linter/source-code-visitor.js:76:30)
    at /Users/scott/src/activescott/ramblefeed/node_modules/eslint/lib/linter/source-code-traverser.js:306:18
    at Array.forEach (<anonymous>)
    at SourceCodeTraverser.traverseSync (/Users/scott/src/activescott/ramblefeed/node_modules/eslint/lib/linter/source-code-traverser.js:305:10)
```